### ISSUE TITLE
TODO 리스트

### ISSUE THREAD

**Issue by JeongMinHo** [mash-up-kr/DoriDori_iOS#2]
- [x] ReactorKit 컨벤션 정하기
- [x] Issue, PR 템플릿 만들기
- [ ] 폴더 구조 정하기
- [ ] MARK 순서 정하기
- [ ] Labels 추가하기
- [ ] ReadMe 정리하기

TBU...
